### PR TITLE
Rof v1

### PR DESCRIPTION
**Pull request by kvanwerkhoven**
[Short description explaining the high-level reason for the pull request]

## Additions
function emtpy_fig to handles cases when no HUCs meet criteria for plotting (no significant rain in the country)
-

## Removals
removed unused functions
-

## Changes
updated to pathlib for file management
many other misc. bug fixes 
-

## Testing

1.

## Notes

-

## Todos

-

### CODE REVIEW

**Comment by kvanwerkhoven** [comment]
@jarq6c @aaraney nwm_utilities.py updates are in, please review.

**Comment by aaraney** [comment]
Awesome @kvanwerkhoven, ill give these a look in 30 or so.

**Comment by kvanwerkhoven** [comment]
I pushed the update to rof_config.py too.  Seems I cannot initiate a separate/new pull request for that update, is that right?  Since part of the same branch it is merged with the nwm_utilities.py pull request?

**Comment by aaraney** [comment]
@kvanwerkhoven, that's right you cannot create a separate pull request. A pull request is just from one branch to another, so if you were to have created a new branch, added changes to it, and pushed those up to the origin repo you could have created a new pull request asking to pull those changes into the main branch of the origin. Does that kind of make sense?

**Comment by kvanwerkhoven** [comment]
Yep, sure does!  Thanks Austin! @aaraney

**Review by aaraney — COMMENTED** [review]
The only snags I ran into when running the code locally that pertinent to this PR transpired when creating directories with `pathlib.Path` objects. Namely, if a parent directory did not exist, this caused pathlib to throw a `FileNotFoundError`. Locally I cleaned up that behavior and got things working in a container. I will push up the changes to the PR to resolve those issues and get this merged.

**Comment by aaraney** [comment]
With the changes I've made in 1c0ef08, I am going to rebase and merge this.

**Comment by kvanwerkhoven** [comment]
@aaraney I've got updates to the figure for WPOD to commit - any reason I should wait on doing a PR for that?

**Comment by aaraney** [comment]
@kvanwerkhoven other than being on vacation, nope. But you will have to create a new branch, commit that changes there and open a pr for that branch.

Your flow should look something like (from your local repo that is on the `rof_v1` branch):
```shell
git stash # stash any changes you've made but haven't committed

git checkout main
git fetch # get changes from remote
git rebase # update your local repo to match the remote

git checkout -b wpod-map-updates # create new local branch called `wpod-map-updates`

git stash pop # Put any changes you had not committed before in the pre-staging area

git add nwm_utilities.py
git commit -m "wpod map changes"
git push origin wpod-map-updates # push changes up to new branch on remote repo call `wpod-map-updates`
```

Right, then you will need to open a PR on GitHub.com

**Comment by aaraney** [comment]
Let me know if you have any questions. Just so you are in the loop (@kvanwerkhoven and @MichaelSmith-NOAA ), I got the code working in a container on Friday and will be deploying that on a VM this afternoon.

**Comment by kvanwerkhoven** [comment]
Got it - thanks @aaraney!  Will do.

**Pull request merged**
